[package]
name = "omnisstream_bench"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "omnisstream_bench"
path = "src/main.rs"

[features]
compression = ["omnisstream/compression"]
group-commit = ["omnisstream/group-commit"]

[dependencies]
anyhow.workspace = true
blake3.workspace = true
clap.workspace = true
libc.workspace = true
omnisstream = { path = "../omnisstream", features = ["bench-relaxed-durability"] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
