#ifndef OMNISSTREAM_FFI_H
#define OMNISSTREAM_FFI_H

#pragma once

// @generated by `cargo run -p omnisstream_ffi --features header-gen --bin omnisstream_ffi_header`
// Do not edit by hand.

#include <stdint.h>
#include <stddef.h>

#define OS_OK 0

#define OS_INVALID_ARGUMENT 1

#define OS_IO_ERROR 2

#define OS_CORRUPT_DATA 3

#define OS_SPEC_VIOLATION 4

#define OS_INTERNAL 5

typedef struct OsManifest OsManifest;

typedef struct OsPartStore OsPartStore;

typedef struct {
  const unsigned char *ptr;
  size_t len;
} OsSpan;

typedef struct {
  unsigned char bytes[32];
} OsDigest;

typedef struct {
  unsigned char *ptr;
  size_t len;
} OsOwnedBytes;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t os_version_major(void);

uint32_t os_version_minor(void);

uint32_t os_version_patch(void);

const char *os_last_error_message(void);

void os_clear_last_error(void);

int os_partstore_open(OsSpan root_utf8, OsPartStore **out_store);

void os_partstore_close(OsPartStore *store);

int os_partstore_put(OsPartStore *store, OsSpan data, OsDigest *out_digest);

int os_partstore_get(OsPartStore *store, const OsDigest *digest, OsOwnedBytes *out_bytes);

void os_owned_bytes_free(OsOwnedBytes *b);

int os_manifest_load_pb(OsSpan pb_bytes, OsManifest **out_manifest);

void os_manifest_free(OsManifest *m);

int os_verify_manifest_on_disk(OsManifest *m, OsSpan base_dir_utf8);

int os_manifest_inspect(OsManifest *m, OsOwnedBytes *out_utf8);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OMNISSTREAM_FFI_H */
